# Generated by Django 4.0 on 2023-09-02 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_createproduct_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='createproduct',
            name='topic',
            field=models.CharField(choices=[('Телефони', 'Телефони'), ('Компютери', 'Компютери'), ('Ноутбуки', 'Ноутбуки'), ('Earphones', 'Earphones'), ('Furniture', 'Меблі'), ('Одяг', 'Clothes')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='createproduct',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Ціна не може бути менше 0'), django.core.validators.MaxValueValidator(limit_value=1000000, message='Ціна не може бути більше 1000')]),
        ),
    ]
