# Generated by Django 4.0 on 2023-09-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_createproduct_topic_alter_createproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproduct',
            name='topic',
            field=models.CharField(choices=[('Телефони', 'Телефони'), ('Компютери', 'Компютери'), ('Ноутбуки', 'Ноутбуки'), ('Earphones', 'Навушники'), ('Furniture', 'Меблі'), ('Одяг', 'Одяг'), ('Техніка', 'Побутова технаіка')], default='', max_length=15),
        ),
    ]
