# Generated by Django 4.0 on 2023-09-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_createproduct_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='createproduct',
            name='site',
            field=models.URLField(default='Write url - address of site where u can buy the product!', max_length=100),
        ),
        migrations.AlterField(
            model_name='createproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='createproduct',
            name='topic',
            field=models.CharField(choices=[('Phones', 'Phones'), ('Computers', 'Computers'), ('Laptops', 'Laptops'), ('Earphones', 'Earphones'), ('Furniture', 'Furniture'), ('TV', 'TV')], default='', max_length=15),
        ),
    ]
