# Generated by Django 4.0 on 2023-09-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_createproduct_site_alter_createproduct_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproduct',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
