# Generated by Django 4.0 on 2023-12-06 19:52

import Store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_createproduct_height_field_createproduct_width_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproduct',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=Store.models.upload_location, width_field='width_field'),
        ),
    ]
