# Generated by Django 4.0 on 2023-08-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='site',
            field=models.URLField(default='Write url - adress of site where u can buy the product!', max_length=100),
        ),
    ]
