# Generated by Django 4.0 on 2023-09-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_price_post_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('життя', 'життя'), ('nature', 'nature'), ('animals', 'тварини'), ('жарти', 'joke')], default='', max_length=15),
        ),
    ]
