# Generated by Django 4.0 on 2023-09-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='site',
            field=models.URLField(default='Write url - address of site where u can buy the product!', max_length=100),
        ),
    ]
